### PR TITLE
Integration of Nucleo f411re

### PR DESCRIPTION
**Pull request by FredPraca**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Hello @FredPraca,

There is not enough difference between the 401 and the 411 to justify to sets of files. The only significant difference is that the memory sizes are different.

I will close this PR and focus on the 401, once the 401 is merged you can make a new PR with just the memory sizes using templates.

**Comment by FredPraca** [comment]
Damn ! I was sure of the 411 integration as I already have the board but I'm a little less confident for the 401 :smile: 
I'll try to make a PR on memory sizes as you recommended

**Comment by FredPraca** [comment]
I checked and I also found: 
* SPI4 clock on APB2 bus in _i-stm32-rcc.ads_
* the SPI5_Base address in _i-stm32.ads_

I'm not sure how to deal with these using templates only, can I ?

**Comment by Fabien-Chouteau** [comment]
As far as the run-time is concerned, we don't care about SPI so don't mind those.

**Comment by FredPraca** [comment]
Ok, so I'll see the impact on Ada_Drivers_Library before creating a pull request on it.

Thanks

**Comment by FredPraca** [comment]
Is it better to provide a runtime for 4x1re boards or provide 401re and 411re based on templating ?

**Pull request closed without merging**
