### PR TITLE
Add support for Nucleo F401RE

### PR DESCRIPTION
**Pull request by FredPraca**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Hello @FredPraca ,

We have new source template system in place and this PR will benefit from using it.

For a file to be handled as a template, it just needs to have a `.tmpl` extension. For instance `memory-map.ld.tmpl`.
And template configuration values are added using the  `add_template_config_value()` function.
For instance in cortexm.py:
```python
self.add_template_config_value('Board_Name', self.board)
```
See:
 - https://github.com/AdaCore/bb-runtimes/blob/1987d2e5d34128336f7c3e6d73d4d4fcb36e2201/support/files_holder.py#L13 
 - https://github.com/AdaCore/bb-runtimes/blob/1987d2e5d34128336f7c3e6d73d4d4fcb36e2201/arm/cortexm.py#L722
 - https://github.com/AdaCore/bb-runtimes/blob/1987d2e5d34128336f7c3e6d73d4d4fcb36e2201/arm/cortexm.py#L705

I'll let you change the code accordingly and open a new PR.

**Comment by FredPraca** [comment]
Ok, which branch should I now use ?
Still community-2020

**Comment by Fabien-Chouteau** [comment]
Yes, you have to rebase since there are new patches on this branch now.

**Comment by damaki** [comment]
> We have new source template system in place and this PR will benefit from using it.
> 
> For a file to be handled as a template, it just needs to have a `.tmpl` extension. For instance `memory-map.ld.tmpl`.
> And template configuration values are added using the `add_template_config_value()` function.
> For instance in cortexm.py:

FYI the current template system on the `community-2020` branch (at commit 3d1542e at the time of writing) doesn't work properly with linker script files (e.g. `memory-map.ld.tmpl` files) due to a bug where the template config values aren't passed to the generator for linker script files. It works fine with Ada source files though.

I've already made a fix for this in #44, but this hasn't been merged yet. The relevant patch to fix this in `support/bsp_sources/archsupport.py` can be found in commit 4c5e438.

**Comment by FredPraca** [comment]
Well at the moment, I ported it similarly to what's done with other boards but compilation fails with a strange error when using _python3 build_rts.py --build --verbose --force --output=/opt/gnat-2020-arm-elf/arm-eabi/lib/gnat nucleo_f411re_ command line:
```
building project /opt/gnat-2020-arm-elf/arm-eabi/lib/gnat/zfp-nucleo_f411re/runtime_build.gpr
Setup
   [mkdir]        object directory for project Runtime_Build
   [mkdir]        library directory for project Runtime_Build
Compile
   [Asm_Cpp]      start-ram.S
   [Asm_Cpp]      start-rom.S
   [Asm_Cpp]      breakpoint_handler-cortexm.S
   [Asm_Cpp]      start-common.S
   [Ada]          s-stm32.ads
   [Ada]          i-stm32-usart.ads
cannot generate code for file s-stm32.ads (package spec)

   compilation of s-stm32.ads failed

```

Any advice welcomed, I've been struggling too long with this port.

**Comment by damaki** [comment]
I think that error occurs when you try to build a package spec (.ads file). It sounds like the `s-stm32.adb` file has not been copied by the runtime.

I looked at the code in your `nucleo_f411re` branch and I think that `s-stm32.adb` is not being copied into the generated runtime.

The problem seems to be in the configuration in `cortexm.py`. On [line 691](https://github.com/FredPraca/bb-runtimes/blob/nucleo_f411re/arm/cortexm.py#L691) you set `self.mcu` to `'stm32f411'`, but then later on [line 731](https://github.com/FredPraca/bb-runtimes/blob/b0375110b4c6c7e8bd1e0f8288de9102a0857b01/arm/cortexm.py#L731) you compare it against `'stm32f411re'` which has an `re` on the end. This means that `s-stm32.adb` is never added to the gnat sources. If you fix that mismatch then I think the error you're seeing will go away.

**Comment by FredPraca** [comment]
Thanks Daniel ! I'll try this but I'm confident that's the problem.
I think it was a bit late when I've done it :smile:

**Pull request closed without merging**
