### PR TITLE
[WIP] Add STM32F103 support

### PR DESCRIPTION
**Pull request by jcassette**
Hello,
I am working on adding STM32F103 support
Any comments are welcome
Julien

### CODE REVIEW

**Comment by jcassette** [comment]
At the moment I am stuck with `setup_pll.adb`
The PLL configuration seems really different from other STM32

**Comment by Fabien-Chouteau** [comment]
Thanks for sharing you work @jcassette,

The STM32F103 is used on the ""blue pill". I know @morbos worked on it: http://www.hrrzi.com/2017/11/ada-on-2-ebay-bluepill-board.html
Maybe you can share the work.

**Comment by jcassette** [comment]
Hi @Fabien-Chouteau 
I use the "Blue Pill" too, thanks for the link.
I am digging into the BSP at https://github.com/morbos/embedded-runtimes/tree/master/bsps/stm32f1/bsp

**Comment by morbos** [comment]
Hi @jcassette, let me know if I can assist you with your Bluepill work.

**Pull request closed without merging**
