### PR TITLE
Add support for STM32F0xx devices

### PR DESCRIPTION
**Pull request by damaki**
### Summary
This adds support for the STM32F0 family of MCUs, based on the ARM Cortex-M0 CPU. All devices in this family are supported: STM32F03x, STM32F04x, STM32F05x, STM320F7x, and STM32F09x.

### Generating runtimes
Runtimes can be generated for any specific device by specifying the full name of the device when calling build_rts.py. For example, `stm32f072rb-hsi` will generate a runtime for the STM32F072RB MCU (128K flash, 16K RAM), and `stm32f072c8-hsi` will generate a runtime for the STM32F072C8 (64K flash, 16K RAM).

The suffix on the target name can be either `-hsi` or `-hse` and determines which clock source is used to derive the system
clock in the generated runtime. For example, 'stm32f072rb-hsi' will generate a runtime using the HSI to generate the system clock, whereas 'stm32f072rb-hse' will generate a runtime using the HSE clock.

The runtime generated using `-hse` assumes that the HSE clock frequency is 8 MHz.

### Code organisation
Although there is existing support for STM32 devices (Cortex-M4 and above) in the `arm/stm32/` directory unfortunately none of this code is compatible with the STM32F0 family as it uses a different CPU architecture (Cortex-M0, ArmV6-M) and there are many differences in clock generation. Therefore, the new code is added to a separate directory `arm/stm32f0xx/` to avoid clashing with the existing STM32 code.

### Ada.Text_IO
I've enabled semihosting I/O by default, but this comes with the caveat that `Ada.Text_IO` can only be used by the user code when the debugger is attached. If a debugger is not attached, then the CPU will HardFault or lockup when any calls are made to `Ada.Text_IO`. 

Unfortunately, the Debug Monitor is not available on the ArmV6-M architecture, so it is not possible to configure the core to resume execution when the BKPT instruction is executed without a debugger (unlike what the ArmV7-M targets can do).

This essentially limits the use of `Ada.Text_IO` to being used for debugging purposes only.

The other possibility is to use `a-textio__null.adb` as the default  implementation for STM32F0 devices, but I thought that the semihosting implementation would be more useful. I have avoided using a UART implementation as choosing the correct UART instance and pinout depends vastly on the specific board used.

### Testing
So far I have built and tested the runtime on a Nucleo-F072RB board using the generated `stm32f072rb-hsi` runtime. The example application blinked the board LED and printed a message via semihosting using Ravenscar delays of 1 second.

I have also generated boards for the `stm32f030c8-hsi` target to confirm that the runtime can be built for different targets, but I do not have other F0 boards to test it on actual hardware.

### TODO
Things still to do:

- [x] Confirm the accuracy of the Ada.Real_Time clock.
- [x] Test that runtimes for other STM32F0 targets are generated and built without errors.
- [x] Test interrupts on a Ravenscar runtime.

Feedback is welcome.

### CODE REVIEW

**Comment by damaki** [comment]
I've checked the accuracy of the `Ada.Real_Time` clock with a simple program that flashes an LED on a Nucleo-F072RB board at 0.5 Hz, and measured the frequency with my Saleae logic analyser. I found PLLMUL was being set incorrected and fixed the problem. With the fixed code I measured a clock error of 0.2% which is well within the HSI clock accuracy of +/- 1%.

**Comment by damaki** [comment]
I've run through and generated ZFP & Ravenscar runtimes for all 63 STM32F0 devices available from ST (see the device list under each of the four lines at https://www.st.com/en/microcontrollers-microprocessors/stm32f0-series.html) for both HSI and HSE variants (126 runtimes total) and fixed any issues found in generating the runtimes.

**Comment by Fabien-Chouteau** [comment]
Thank you @damaki!

This is very impressive, I like the trick to configure the run-time based on its name :+1:

**Comment by damaki** [comment]
Thanks! Hopefully the generation based on the device name will make it easier for users to create the correct run-time for their specific device without needing to know how to customise the generated runtimes. We could also use the same technique to customise other boards/devices in bb-runtimes, but that would be separate from this pull request.

I know that generated runtimes are usually distributed with GNAT Community, but for these new STM32F0 devices it's probably sensible to distribute only a few runtimes for selected targets. Otherwise, generating 3 runtimes (zfp, ravenscar-sfp, and ravenscar-full) for 63 targets and 2 clock configurations (HSI/HSE) results in 378 possible runtimes! That's almost 3 GB on my machine.

So instead, if these runtimes will be distributed then I would recommend only distributing run-times for the Nucleo 64 boards provided by ST (see https://www.st.com/en/evaluation-tools/stm32-nucleo-boards.html):
* Nucleo-F030R8 (`stm32f030r8-hsi` and `stm32f030r8-hse`)
* Nucleo-F031K6 (`stm32f031k6-hsi` and `stm32f031k6-hse`)
* Nucleo-F042K6 (`stm32f042k6-hsi` and `stm32f042k6-hse`)
* Nucleo-F070RB (`stm32f070rb-hsi` and `stm32f070rb-hse`)
* Nucleo-F072RB (`stm32f072rb-hsi` and `stm32f072rb-hse`)
* Nucleo-F091RC (`stm32f091rc-hsi` and `stm32f091rc-hse`)

Anyway, I've finished checking that interrupts are working in the Ravenscar runtimes. I set up a periodic interrupt using TIM2 to flash an LED, and it seems to work perfectly fine. So all of my outstanding TODOs are now done.

Please let me know if you need any other changes.

**Comment by Fabien-Chouteau** [comment]
Hello @damaki, we are in the middle of our release process so we won't pull changes just now.
We will have a look at this in couple weeks, don't hesitate to ping us.

**Comment by Fabien-Chouteau** [comment]
Hello again @damaki,

I think this PR will benefit from the template system. In particular to lower the large number of file variants (linker script, s-bbbopa, s-bbmcpa).

For a file to be handled as a template, it just needs to have a `.tmpl` extensio. For instance `memory-map.ld.tmpl`.
And template configuration values are added using the  `add_template_config_value()` function.
For instance in cortexm.py:
```python
self.add_template_config_value('Board_Name', self.board)
```

I'll you change the code accordingly and open a new PR.

Thanks in advance,

**Comment by damaki** [comment]
Thanks Fabien. I've taken a quick look at the new template feature and I agree; this PR would benefit from it. I'll follow your advice and submit a new PR with the requested changes.

**Pull request closed without merging**
